export const symbols = [
  "BTCUSDT", "ETHUSDT", "BNBUSDT", "SOLUSDT", "XRPUSDT",
  "DOGEUSDT", "ADAUSDT", "AVAXUSDT", "DOTUSDT", "LINKUSDT",
  "LTCUSDT", "MATICUSDT", "SHIBUSDT", "FTMUSDT", "TRXUSDT",
  "BNBETH", "FETUSDT", "ETHBTC", "BUSDUSDT", "USDTUSDT",
  "AAVEUSDT", "MANAUSDT", "DOGEUSDT", "LUNAUSDT", "LTCUSDT",
  // add up to 500 symbols
];

